services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./application:/var/www/html
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - .docker/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .docker/php-fpm
    env_file:
      - .docker/php-fpm/.env
    volumes:
      - ./application:/var/www/html

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: comix
      POSTGRES_PASSWORD: comix
      POSTGRES_DB: comix
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI

  pgadmin:
    image: elestio/pgadmin:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@comix.dummy
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin-data:
